# Generated by Django 4.0.3 on 2022-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
