# Generated by Django 4.0.3 on 2022-03-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_last_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Profile',
        ),
    ]
