# Generated by Django 4.0.3 on 2022-04-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_department_intitute_alter_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='intitute',
            new_name='institute',
        ),
    ]
